[package]
name = "axum-quickstart"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"]}
axum = { version = "0.7.5" }
tower = { version = "0.4.13" }
futures-util = { version = "0.3.30" }
tower-http = { version = "0.5.2", features = ["full"] }